// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-60f6lo05TccNldu1wGH-l_JekwxEPoU',
    appId: '1:371227749929:web:3384b5a210f52c9e7c3638',
    messagingSenderId: '371227749929',
    projectId: 'itds283-9edc7',
    authDomain: 'itds283-9edc7.firebaseapp.com',
    storageBucket: 'itds283-9edc7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPzm9ibW_1DDQGFt2XZtG3Fk7B-lEtWUk',
    appId: '1:371227749929:android:6a5c1c8313dfaf767c3638',
    messagingSenderId: '371227749929',
    projectId: 'itds283-9edc7',
    storageBucket: 'itds283-9edc7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3vW-hia27_Yyl3MwKJVvSA_XXlfIxLhw',
    appId: '1:371227749929:ios:2ed479731f2826d27c3638',
    messagingSenderId: '371227749929',
    projectId: 'itds283-9edc7',
    storageBucket: 'itds283-9edc7.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3vW-hia27_Yyl3MwKJVvSA_XXlfIxLhw',
    appId: '1:371227749929:ios:2ed479731f2826d27c3638',
    messagingSenderId: '371227749929',
    projectId: 'itds283-9edc7',
    storageBucket: 'itds283-9edc7.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-60f6lo05TccNldu1wGH-l_JekwxEPoU',
    appId: '1:371227749929:web:c5249ab208249c8c7c3638',
    messagingSenderId: '371227749929',
    projectId: 'itds283-9edc7',
    authDomain: 'itds283-9edc7.firebaseapp.com',
    storageBucket: 'itds283-9edc7.appspot.com',
  );

}