// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfGMgwfewGofZfMTbuiy-1Ety3Ari1SkQ',
    appId: '1:608457991666:web:bc4a0334217f4be8c4376b',
    messagingSenderId: '608457991666',
    projectId: 'project-fd376',
    authDomain: 'project-fd376.firebaseapp.com',
    storageBucket: 'project-fd376.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZd8i10sAqOz32PbtztSrNPhvsYurbA0w',
    appId: '1:608457991666:android:d16740b60a617ba9c4376b',
    messagingSenderId: '608457991666',
    projectId: 'project-fd376',
    storageBucket: 'project-fd376.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVN6r0kamzcineokAtJuFPErlO13DD0KU',
    appId: '1:608457991666:ios:d3816de460b4e940c4376b',
    messagingSenderId: '608457991666',
    projectId: 'project-fd376',
    storageBucket: 'project-fd376.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVN6r0kamzcineokAtJuFPErlO13DD0KU',
    appId: '1:608457991666:ios:d3816de460b4e940c4376b',
    messagingSenderId: '608457991666',
    projectId: 'project-fd376',
    storageBucket: 'project-fd376.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfGMgwfewGofZfMTbuiy-1Ety3Ari1SkQ',
    appId: '1:608457991666:web:b1aed62c0363ad26c4376b',
    messagingSenderId: '608457991666',
    projectId: 'project-fd376',
    authDomain: 'project-fd376.firebaseapp.com',
    storageBucket: 'project-fd376.appspot.com',
  );
}
